ARG IMAGE_SHA=sha256:9975044ddd0290a6822a56c109ea36d9c4b7ff02ab93c42a6525564a484ebffa

# mcr.microsoft.com/devcontainers/python:dev-3.14-trixie
FROM mcr.microsoft.com/devcontainers/python@${IMAGE_SHA}